<?php
$autoload = $argv[1] ?? '';
if (!is_file($autoload)) throw new RuntimeException('Pass application vendor/autoload.php');
require dirname(__DIR__) . '/src/Tools/Http/ElasticHttpPool.php';
require $autoload;
use Dleno\CommonCore\Tools\Http\ElasticHttpPool as Pool;
function check($v,$m){if(!$v)throw new RuntimeException($m);}
Swoole\Coroutine\run(function(){
 $server=new Swoole\Coroutine\Http\Server('127.0.0.1',0,false);
 $origin='http://127.0.0.1:'.$server->port;
 $receipts=[];$healthHosts=[];
 $server->handle('/',function($q,$r)use(&$receipts,&$healthHosts){if(($q->header['user-agent']??'')==='common-core-http-health/1')$healthHosts[]=$q->header['host']??'';$id=$q->header['x-id']??'health';$receipts[$id]=($receipts[$id]??0)+1;if($q->server['request_uri']==='/slow')Swoole\Coroutine::sleep(.15);if($q->server['request_uri']==='/timeout')Swoole\Coroutine::sleep(.3);if($q->server['request_uri']==='/500')$r->status(500);if($q->server['request_uri']==='/closed-health')$r->header('Connection','close');$r->end(json_encode([$id,$q->rawContent(),$q->header['cookie']??'', $q->server['query_string']??'', $q->server['remote_port']]));});
 Swoole\Coroutine::create(fn()=>$server->start());
 $opts=['min_connections'=>2,'health_path'=>null,'max_idle_time'=>.25,'transport'=>['defer'=>true,'timeout'=>10,'read_timeout'=>10,'write_timeout'=>10,'max_retries'=>2,'lowercase_header'=>false]];
 $call=function($id,$path='/slow',$timeout=2)use($opts,$origin){return Pool::request('driver',$origin.$path,'body'.$id,'POST',['X-Id'=>(string)$id],$timeout,$opts);};
 Pool::request('failed-round',$origin.'/','x','POST',['X-Id'=>'business'],2,['min_connections'=>0,'health_path'=>null]);
 $p=array_values((new ReflectionProperty(Pool::class,'pools'))->getValue())[0];
 (new ReflectionProperty($p,'options'))->setValue($p,['min_connections'=>6,'health_path'=>'/closed-health','health_method'=>'GET']);
 (new ReflectionMethod($p,'maintain'))->invoke($p);Swoole\Coroutine::sleep(.05);
 $stat=array_values(Pool::statistics())[0];check($stat['maintenanceFailures']===1,'five failed connections count as one reconnect round');
 $delay=(new ReflectionProperty($p,'retryAt'))->getValue($p)-(hrtime(true) / 1_000_000_000);
 check($delay>0&&$delay<3,'first reconnect round must back off 2 seconds instead of 30');Pool::shutdown();
 $low=['min_connections'=>2,'health_path'=>null,'max_idle_time'=>60];
 $first=Pool::request('sparse',$origin.'/','x','POST',[],2,$low);
 $p=array_values((new ReflectionProperty(Pool::class,'pools'))->getValue())[0];
 (new ReflectionProperty($p,'lastBusinessAt'))->setValue($p,(hrtime(true) / 1_000_000_000)-40);
 $idle=new ReflectionProperty($p,'idle');$entries=$idle->getValue($p);$entries[0]['released']=(hrtime(true) / 1_000_000_000)-40;$idle->setValue($p,$entries);
 $second=Pool::request('sparse',$origin.'/','y','POST',[],2,$low);
 check(json_decode($first['body'],true)[4]===json_decode($second['body'],true)[4],'sparse traffic reuses valid idle instead of forcing cold connection');
 check(array_values(Pool::statistics())[0]['created']===1,'sparse traffic does not force floor growth');
 (new ReflectionProperty($p,'lastBusinessAt'))->setValue($p,(hrtime(true) / 1_000_000_000)-29);
 Pool::request('sparse',$origin.'/','z','POST',[],2,$low);
 check(array_values(Pool::statistics())[0]['created']===1,'one short interval after a long interval does not force growth');Pool::shutdown();
 $invalid=['min_connections'=>2,'health_path'=>'/','health_method'=>'POST'];
 $before=$receipts['health'];Pool::request('invalid-health',$origin.'/','x','POST',['X-Id'=>'invalid-health'],2,$invalid);
 check(!array_values(Pool::statistics())[0]['healthConfigured']&&$receipts['health']===$before,'invalid health method must not probe or destroy business connections');Pool::shutdown();
 $short=['min_connections'=>0,'health_path'=>null,'max_idle_time'=>.05];
 Pool::request('ttl',$origin.'/','x','POST',[],2,$short);
 Swoole\Coroutine::sleep(.08);
 check(array_values(Pool::statistics())[0]['live']===0,'expired unprobed connection is not counted as effective');
 Pool::request('ttl',$origin.'/','y','POST',[],2,$short);
 check(array_values(Pool::statistics())[0]['created']===2,'checkout enforces TTL before maintenance tick');
 Pool::shutdown();
 $a=$call('a','/');$b=$call('b','/');check($a['errCode']===0&&$b['errCode']===0,'sequential transport');
 check(array_values(Pool::statistics())[0]['live']===2,'real business floor');
 $c=$call('c','/');$d=$call('d','/');
 check(json_decode($c['body'],true)[4]===json_decode($a['body'],true)[4]
    && json_decode($d['body'],true)[4]===json_decode($b['body'],true)[4],'sequential requests rotate both floor connections');
 $channel=new Swoole\Coroutine\Channel(64);
 for($i=0;$i<64;$i++)Swoole\Coroutine::create(function()use($call,$channel,$i){$r=$call($i);$channel->push([$i,$r]);});
 for($i=0;$i<64;$i++){[$id,$r]=$channel->pop();check($r['errCode']===0,'burst transport');check(json_decode($r['body'],true)[0]===(string)$id,'exclusive response');}
 $stat=array_values(Pool::statistics())[0];check($stat['created']>=64,'unbounded beyond32');
 $r=$call('failure','/500');check($r['statusCode']===500&&$receipts['failure']===1,'500 one attempt');
 $r=$call('timeout','/timeout',.05);check($r['errCode']!==0&&$receipts['timeout']===1,'timeout one attempt');
 Swoole\Coroutine::sleep(1.2);check(array_values(Pool::statistics())[0]['live']===0,'unprobed idle sockets expire even at floor');
 Pool::shutdown();
 $o=['min_connections'=>5,'health_path'=>'/','health_method'=>'GET','heartbeat'=>.1,'max_idle_time'=>.1];
 Pool::request('internal',$origin.'/','x','POST',[],2,$o);
 Swoole\Coroutine::sleep(.1);check(array_values(Pool::statistics())[0]['live']>=5,'internal warm live5');
 $done=new Swoole\Coroutine\Channel(8);
 for($i=0;$i<8;$i++)Swoole\Coroutine::create(function()use($origin,$o,$done){$done->push(Pool::request('internal',$origin.'/slow','x','POST',[],2,$o));});
 for($i=0;$i<8;$i++)check($done->pop()['errCode']===0,'internal burst');
 Swoole\Coroutine::sleep(1.2);check(array_values(Pool::statistics())[0]['live']===5,'heartbeat does not prevent excess idle eviction');
 // Fault injection: backoff for a failed new connection must not suspend healthy socket probes.
 $registry=new ReflectionProperty(Pool::class,'pools');$pool=array_values($registry->getValue())[0];
 $retry=new ReflectionProperty($pool,'retryAt');$retry->setValue($pool,(hrtime(true) / 1_000_000_000)+30);
 $idle=new ReflectionProperty($pool,'idle');$entries=$idle->getValue($pool);
 foreach($entries as &$entry)$entry['checked']=(hrtime(true) / 1_000_000_000)-1;unset($entry);$idle->setValue($pool,$entries);
 $before=$receipts['health'];(new ReflectionMethod($pool,'maintain'))->invoke($pool);Swoole\Coroutine::sleep(.03);
 check($receipts['health']>$before,'reconnect backoff must not suspend healthy heartbeat');check($retry->getValue($pool)>(hrtime(true) / 1_000_000_000),'heartbeat must not clear reconnect backoff');$retry->setValue($pool,0);
 $failures=new ReflectionProperty($pool,'failures');$failures->setValue($pool,5);$retry->setValue($pool,(hrtime(true) / 1_000_000_000)+30);
 Pool::request('internal',$origin.'/','recovered','POST',['X-Id'=>'recovered'],2,$o);
 check($failures->getValue($pool)===0&&$retry->getValue($pool)===0.0,'business recovery at floor resets reconnect backoff');
 $finishing=new Swoole\Coroutine\Channel(1);
 Swoole\Coroutine::create(function()use($origin,$o,$finishing){$finishing->push(Pool::request('internal',$origin.'/slow','finishing','POST',[],2,$o));});
 Swoole\Coroutine::sleep(.02);
 \Hyperf\Coordinator\CoordinatorManager::until(\Hyperf\Coordinator\Constants::WORKER_EXIT)->resume();
 Swoole\Coroutine::sleep(.01);check(array_values(Pool::statistics())[0]['idle']===0,'worker exit closes idle');
 check(!array_filter($healthHosts,fn($host)=>$host!==substr($origin,7)),'health Host includes the actual non-default port');
 check($finishing->pop()['errCode']===0,'worker exit preserves busy request');
 check(array_values(Pool::statistics())[0]['live']===0,'finished lease closes after worker exit');
 $before=$receipts['health'];
 check(Pool::request('exit-new',$origin.'/','x','POST',['X-Id'=>'closing'],2,$o)['errCode']===0,'in-flight business can reach new origin during exit');
 check($receipts['health']===$before,'exit must not start new health probes');
 Pool::shutdown();$server->shutdown();echo json_encode(['burst'=>64,'peakCreated'=>$stat['created'],'floor'=>2,'internal'=>5,'oneAttempt500Timeout'=>true])."\n";
});
